from pathlib import Path
hp=Path('artifacts/project-ice/index.html')
gp=Path('artifacts/project-ice/public/game.js')
sp=Path('artifacts/project-ice/public/style.css')
h=hp.read_text(); g=gp.read_text(); s=sp.read_text()

# Insert Rival Watch immediately before Scout Summary.
marker='''              <div class="pp-scouting-evaluation">\n'''
block='''              <div class="pp-scouting-rival" id="pp-scouting-rival-watch">\n                <div class="pp-scouting-rival__header">\n                  <div>\n                    <span class="pp-scouting-rival__eyebrow">Prospect Race</span>\n                    <strong>Rival Watch</strong>\n                  </div>\n\n                  <span class="pp-scouting-rival__rank" id="pp-scouting-rival-current-rank">\n                    Not Ranked\n                  </span>\n                </div>\n\n                <p class="pp-scouting-rival__empty" id="pp-scouting-rival-empty">\n                  Earn a published scouting ranking to unlock the prospect race around you.\n                </p>\n\n                <div class="pp-scouting-rival__grid" id="pp-scouting-rival-grid" hidden>\n                  <article class="pp-scouting-rival-card">\n                    <span class="pp-scouting-rival-card__label">Just Ahead</span>\n                    <strong id="pp-scouting-rival-above-name">—</strong>\n                    <span id="pp-scouting-rival-above-meta">—</span>\n                  </article>\n\n                  <article class="pp-scouting-rival-card pp-scouting-rival-card--position">\n                    <span class="pp-scouting-rival-card__label">Position Rival</span>\n                    <strong id="pp-scouting-rival-position-name">—</strong>\n                    <span id="pp-scouting-rival-position-meta">—</span>\n                  </article>\n\n                  <article class="pp-scouting-rival-card">\n                    <span class="pp-scouting-rival-card__label">On Your Heels</span>\n                    <strong id="pp-scouting-rival-below-name">—</strong>\n                    <span id="pp-scouting-rival-below-meta">—</span>\n                  </article>\n                </div>\n              </div>\n\n'''
if 'id="pp-scouting-rival-watch"' not in h:
    if marker not in h: raise SystemExit('scout summary marker missing')
    h=h.replace(marker,block+marker,1)

# Render visible Rival Watch from canonical scouting profile.
anchor='''    const scoutingHistory =\n      Array.isArray(\n        scouting.scoutingHistory\n      )\n        ? scouting.scoutingHistory\n        : [];\n'''
insert='''    const rivalWatch =\n      scouting.rivalWatch &&\n      typeof scouting.rivalWatch === 'object'\n        ? scouting.rivalWatch\n        : null;\n\n    const rivalCurrentRank =\n      document.getElementById(\n        'pp-scouting-rival-current-rank'\n      );\n\n    const rivalEmpty =\n      document.getElementById(\n        'pp-scouting-rival-empty'\n      );\n\n    const rivalGrid =\n      document.getElementById(\n        'pp-scouting-rival-grid'\n      );\n\n    const escapeScoutingText = value =>\n      String(value ?? '')\n        .replace(/&/g, '&amp;')\n        .replace(/</g, '&lt;')\n        .replace(/>/g, '&gt;')\n        .replace(/"/g, '&quot;')\n        .replace(/'/g, '&#039;');\n\n    const renderRival = (\n      prefix,\n      rival\n    ) => {\n      const nameElement =\n        document.getElementById(\n          `pp-scouting-rival-${prefix}-name`\n        );\n      const metaElement =\n        document.getElementById(\n          `pp-scouting-rival-${prefix}-meta`\n        );\n\n      if (!nameElement || !metaElement) return;\n\n      if (!rival) {\n        nameElement.textContent = 'No nearby prospect';\n        metaElement.textContent = '—';\n        return;\n      }\n\n      nameElement.textContent =\n        rival.name ||\n        'Prospect';\n\n      const rank =\n        Math.max(0, Number(rival.rank) || 0);\n      const position = rival.position || '—';\n      const teamName = rival.teamName || null;\n      const movement = Number(rival.rankChange) || 0;\n      const movementText =\n        movement > 0\n          ? `▲ ${movement}`\n          : movement < 0\n            ? `▼ ${Math.abs(movement)}`\n            : null;\n\n      metaElement.textContent = [\n        rank > 0 ? `#${rank}` : null,\n        position,\n        movementText,\n        teamName,\n      ].filter(Boolean).join(' • ');\n    };\n\n    const rankedForRivalWatch =\n      Boolean(\n        rivalWatch &&\n        Number(rivalWatch.currentRank) > 0\n      );\n\n    if (rivalCurrentRank) {\n      rivalCurrentRank.textContent =\n        rankedForRivalWatch\n          ? `#${Number(rivalWatch.currentRank)}`\n          : 'Not Ranked';\n    }\n\n    if (rivalEmpty) {\n      rivalEmpty.hidden =\n        rankedForRivalWatch;\n    }\n\n    if (rivalGrid) {\n      rivalGrid.hidden =\n        !rankedForRivalWatch;\n    }\n\n    if (rankedForRivalWatch) {\n      renderRival('above', rivalWatch.above);\n      renderRival('position', rivalWatch.positionRival);\n      renderRival('below', rivalWatch.below);\n    }\n'''
if 'const rivalWatch =' not in g:
    if anchor not in g: raise SystemExit('scouting history anchor missing')
    g=g.replace(anchor,insert+'\n'+anchor,1)

# CSS visual language: compact, dark glass, selective blue/gold accents.
css='''\n\n/* Player Scouting — Rival Watch */\n.pp-scouting-rival {\n  margin: 14px 0;\n  padding: 14px;\n  border: 1px solid rgba(255,255,255,0.08);\n  border-radius: 16px;\n  background: rgba(255,255,255,0.035);\n}\n\n.pp-scouting-rival__header {\n  display: flex;\n  align-items: center;\n  justify-content: space-between;\n  gap: 12px;\n  margin-bottom: 12px;\n}\n\n.pp-scouting-rival__header > div {\n  display: grid;\n  gap: 3px;\n}\n\n.pp-scouting-rival__eyebrow {\n  color: rgba(255,255,255,0.48);\n  font-size: 0.68rem;\n  font-weight: 800;\n  letter-spacing: 0.14em;\n  text-transform: uppercase;\n}\n\n.pp-scouting-rival__header strong {\n  color: #f5f7fb;\n  font-size: 0.98rem;\n}\n\n.pp-scouting-rival__rank {\n  flex: 0 0 auto;\n  padding: 6px 10px;\n  border: 1px solid rgba(109,168,255,0.36);\n  border-radius: 999px;\n  background: rgba(69,124,208,0.12);\n  color: #9dc5ff;\n  font-size: 0.74rem;\n  font-weight: 850;\n  letter-spacing: 0.04em;\n}\n\n.pp-scouting-rival__empty {\n  margin: 0;\n  color: rgba(255,255,255,0.5);\n  font-size: 0.82rem;\n  line-height: 1.45;\n}\n\n.pp-scouting-rival__grid {\n  display: grid;\n  grid-template-columns: 1fr;\n  gap: 8px;\n}\n\n.pp-scouting-rival__grid[hidden] {\n  display: none;\n}\n\n.pp-scouting-rival-card {\n  display: grid;\n  gap: 4px;\n  padding: 11px 12px;\n  border: 1px solid rgba(255,255,255,0.07);\n  border-radius: 12px;\n  background: rgba(6,10,18,0.34);\n}\n\n.pp-scouting-rival-card--position {\n  border-color: rgba(214,174,92,0.22);\n  background: rgba(151,107,38,0.07);\n}\n\n.pp-scouting-rival-card__label {\n  color: rgba(255,255,255,0.42);\n  font-size: 0.64rem;\n  font-weight: 800;\n  letter-spacing: 0.12em;\n  text-transform: uppercase;\n}\n\n.pp-scouting-rival-card strong {\n  color: #eef4ff;\n  font-size: 0.9rem;\n}\n\n.pp-scouting-rival-card > span:last-child {\n  color: rgba(255,255,255,0.56);\n  font-size: 0.74rem;\n  line-height: 1.35;\n}\n'''
if '/* Player Scouting — Rival Watch */' not in s:
    s += css

hp.write_text(h); gp.write_text(g); sp.write_text(s)
print('added visible Player-tab Rival Watch')
