from pathlib import Path
p=Path('artifacts/project-ice/public/world.js')
s=p.read_text()
old="""  async function listCareerSaves() {\n    /* Ensure a legacy single save is migrated before the list is shown. */\n    if (readCareerSaveIndex().length === 0) {\n      await load();\n    }\n    return readCareerSaveIndex().slice().sort((a, b) => String(b?.savedAt || '').localeCompare(String(a?.savedAt || '')));\n  }\n"""
new="""  async function listCareerSaves() {\n    let index = readCareerSaveIndex();\n\n    /*\n     * LEGACY SINGLE-SAVE → MULTI-SAVE MIGRATION\n     *\n     * On old installs the title boot has already loaded the IndexedDB\n     * `default` world into _state. The first time the player opens\n     * Continue Career, preserve that exact loaded world as slot #1.\n     * Keeping the legacy record untouched gives us a recovery copy.\n     */\n    if (index.length === 0) {\n      const hasCareerPlayer =\n        Boolean(\n          getPlayerById(\n            _state.player?.playerId ||\n            _state.player?.id ||\n            'career-player'\n          )\n        ) ||\n        (_state.teams || []).some(team =>\n          (team?.roster || []).some(player =>\n            player?.isCareerPlayer === true ||\n            String(player?.id || player?.playerId || '') === 'career-player'\n          )\n        );\n\n      if (hasCareerPlayer) {\n        const careerId = createCareerSaveId();\n        localStorage.setItem(\n          ACTIVE_CAREER_ID_KEY,\n          careerId\n        );\n\n        const migrated = await save();\n\n        if (migrated) {\n          index = readCareerSaveIndex();\n        }\n      }\n    }\n\n    return index\n      .slice()\n      .sort((a, b) =>\n        String(b?.savedAt || '')\n          .localeCompare(\n            String(a?.savedAt || '')\n          )\n      );\n  }\n"""
if old not in s: raise SystemExit('legacy listCareerSaves block not found')
s=s.replace(old,new,1)
s=s.replace("""        resolvedRecord?.world &&\n        typeof storedRecord.world ===\n          'object'\n""","""        resolvedRecord?.world &&\n        typeof resolvedRecord.world ===\n          'object'\n""",1)
p.write_text(s)
print('finalized multi-save migration')
