from pathlib import Path

path = Path('artifacts/project-ice/public/game.js')
text = path.read_text(encoding='utf-8')

old = """  // Add all fictional high-school roster players.\n  const generatedProspects = teams.flatMap(team => {\n    const roster = Array.isArray(team.roster) ? team.roster : [];\n\n    return roster\n      .filter(player => {\n        // Hide the fictional player occupying the user's roster slot.\n        const isReplacedByUser =\n          team.teamId === playerTeamId &&\n          player.rosterSlot === userRosterSlot;\n\n        return !isReplacedByUser;\n      })\n      .map(player => ({\n        ...player,\n\n        sourceType: 'fictional-hs',\n        isUser: false,\n        realPlayer: false,\n\n        schoolName: team.schoolName,\n        teamName: team.teamName,\n        teamAbbreviation: `${team.schoolName} ${team.teamName}`\n          .split(/\\s+/)\n          .filter(Boolean)\n          .map(word => word[0])\n          .join('')\n          .toUpperCase(),\n\n        league: 'HS',\n      }));\n  });\n\n  // Add all real 2027-and-younger prospects.\n  const realProspects =\n    typeof REAL_PROSPECTS !== 'undefined' &&\n    Array.isArray(REAL_PROSPECTS)\n      ? REAL_PROSPECTS.map(player => ({\n          ...player,\n\n          sourceType: 'real',\n          isUser: false,\n          realPlayer: true,\n\n          // These allow the same renderer to handle every player type.\n          schoolName: '',\n          teamName: player.currentTeam || '',\n          teamAbbreviation:\n            player.teamAbbreviation ||\n            String(player.currentTeam || '—')\n              .split(/\\s+/)\n              .filter(Boolean)\n              .map(word => word[0])\n              .join('')\n              .toUpperCase(),\n        }))\n      : [];\n"""

new = """  // Add all high-school roster players. Real prospects moved into a Project\n  // Ice HS program remain the same canonical player.\n  const generatedProspects = teams.flatMap(team => {\n    const roster = Array.isArray(team.roster) ? team.roster : [];\n\n    return roster\n      .filter(player => {\n        const isReplacedByUser =\n          team.teamId === playerTeamId &&\n          player.rosterSlot === userRosterSlot;\n        return !isReplacedByUser;\n      })\n      .map(player => {\n        const isRosteredRealProspect = Boolean(\n          player?.realPlayer ||\n          player?.isRealProspect ||\n          String(player?.id || player?.playerId || '').startsWith('real-')\n        );\n\n        return {\n          ...player,\n          sourceType: isRosteredRealProspect ? 'real-hs' : 'fictional-hs',\n          isUser: false,\n          realPlayer: isRosteredRealProspect,\n          schoolName: team.schoolName,\n          teamName: team.teamName,\n          teamAbbreviation: `${team.schoolName} ${team.teamName}`\n            .split(/\\s+/)\n            .filter(Boolean)\n            .map(word => word[0])\n            .join('')\n            .toUpperCase(),\n          league: 'HS',\n        };\n      });\n  });\n\n  // A real player rostered in the Project Ice HS world must appear only once.\n  // Keep the HS/world copy and suppress the historical real-team database row\n  // from the fallback ranking pool.\n  const rosteredRealProspectIds = new Set(\n    generatedProspects\n      .filter(player => player.realPlayer)\n      .map(player => String(player.id || player.playerId || ''))\n      .filter(Boolean)\n  );\n\n  const realProspects =\n    typeof REAL_PROSPECTS !== 'undefined' &&\n    Array.isArray(REAL_PROSPECTS)\n      ? REAL_PROSPECTS\n          .filter(player => {\n            const playerId = String(player?.id || player?.playerId || '');\n            return !playerId || !rosteredRealProspectIds.has(playerId);\n          })\n          .map(player => ({\n            ...player,\n            sourceType: 'real',\n            isUser: false,\n            realPlayer: true,\n            schoolName: '',\n            teamName: player.currentTeam || '',\n            teamAbbreviation:\n              player.teamAbbreviation ||\n              String(player.currentTeam || '—')\n                .split(/\\s+/)\n                .filter(Boolean)\n                .map(word => word[0])\n                .join('')\n                .toUpperCase(),\n          }))\n      : [];\n"""

count = text.count(old)
if count != 1:
    raise SystemExit(f'expected exactly 1 fallback prospect-pool block, found {count}')

text = text.replace(old, new, 1)
path.write_text(text, encoding='utf-8')
print('ROSTERED_REAL_PROSPECT_DEDUPE=PASS')
